### ISSUE TITLE
Implement magVar to bearing() 

### ISSUE THREAD

**Issue by RIZY101** [Dameech92/AMEL#94]
Once bearing() is correctly fixed we must take the result and apply the magnetic variation to it. 
This might be a good place to start https://stackoverflow.com/questions/19992527/convert-user-entered-true-azimuth-to-magnetic-azimuth?rq=1

**Comment by rjzins** [comment]
The method above would work well if not flying. However, wind can be significant at altitude (150 knots!), so that makes the GPS track significantly different than heading, and can be much bigger than say if driving, so with a big wind you would get a false magyar calculation (because the method above just takes the difference between track and heading and track will be contaminated by large airborne winds.). A better way to do this is to import the magnetic variation model class linked below, calculate it at Bullseye, and apply it to the bearing. That way this class/object only has to be called and calculated once - the MagVar at Bullseye won't be much different than at current location, so it is more efficient to just calculate it at bullseye, and apply that number to your true bearing from bullseye to present location. To go from True to Magnetic, you add West variation and subtract East. See this project, I think it will be easier and more accurate than the other method mentioned by RIZY101. https://github.com/kanchudeep/Geomagnetism-Swift

**Comment by neil-marcellini** [comment]
I applied the magnetic declination the the true bearing. Please let me know if the way I did it is correct. [See branch](https://github.com/Dameech92/AMEL/pull/96)

**Comment by neil-marcellini** [comment]
I just added another commit to make sure that magnetic bearings are valid, by [taking the modulus 360.](https://github.com/Dameech92/AMEL/commit/983a3fa2e49e6cbc24dafaab1dc1fd4001c54f6f) 
@RIZY101 @rjzins

**Comment by RIZY101** [comment]
@neil-marcellini This looks correct to @rjzins and me. We are going to test locally and if all goes according to plan approve the merge.
